### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [vlastikczech/FirehoseSplurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by vlastikwalker** [comment]
Figured it out. Added <meta name="viewport" content="width=device-width,
initial-scale=1"> to the application. and then tested it using the
developer tool that chrome has.

**Comment by Mikeysax** [comment]
Awesome 👍
